### ISSUE TITLE
Difficulty running getAppState

### ISSUE THREAD

**Issue by Switcherag** [shellcxd3/AAAAAAAAAAAAA#4]
Hey, can't log in messenger bot so i tried your script 👍 

 const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for selector `div[role=feed]` failed: timeout 30000ms exceeded
    at new WaitTask (AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (D:\Users\Switcherag\Bureau\AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (AAAAAAAAAAAAA-main\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1333:33)
    at AAAAAAAAAAAAA-main\getAppstate.js:19:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I constantly get this error. I also tried to put await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36')

Don't throw error but don't give the json file.

Any help would be appreciated

**Comment by Th3OnlyN00b** [comment]
Change this line to be page.waitForNavigation(), that should fix your issue and let you login.

**Comment by shellmage** [comment]
heyy @Switcherag @Th3OnlyN00b , it's been a while since I last logged in to github,
If this issue is solved and you guys wanna contribute to this open-source project,
feel free to open a pull request so that I can mark the issue as closed/completed for future users,
*this was just a weekend project to mess around with friends from [OpenMindsClub](https://github.com/openmindsclub) on a messenger group back when I was still on facebook, I didn't think other people will use it, it means a lot to me*
